# https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes#step-5-%E2%80%94-enabling-pod-communication-through-the-load-balancer-(optional)
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: lightcoker@gapp.nthu.edu.tw
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: passmanager-tls
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx