apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password # label for this deployment to find corresponding pods
  template:
    metadata:
      labels:
        app: password # label for pods
    spec:
      containers:
        - name: password
          image: lightcoker/passmanager-password
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_HOST
              value: password-mongo-clusterip
            - name: MONGO_USER
              value: mongo
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongopassword
                  key: MONGO_PASSWORD
            - name: MONGO_DB_NAME
              value: password
            - name: MONGO_PORT
              value: "27017"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-clusterip:4222'
            - name: NATS_CLUSTER_ID
              value: passmanager
---
apiVersion: v1
kind: Service
metadata: 
  name: password-clusterip
spec:
  type: ClusterIP
  selector:
    app: password
  ports:
    - name: password
      protocol: TCP
      port: 3000
      targetPort: 3000 
