apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-redis
  template:
    metadata:
      labels:
        app: query-redis
    spec:
      containers:
        - name: query-redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata: 
  name: query-redis-clusterip
spec:
  type: ClusterIP
  selector:
    app: query-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379 # redis default port
      targetPort: 6379 
