name: deploy-auth

# Manual event
on: workflow_dispatch 

jobs:
  build:
    name: deploy auth service
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code on the repository
        uses: actions/checkout@v2

      - name: build docker image
        run: cd auth && docker build -t $DOCKER_USERNAME/$PROJECT_NAME-auth .
      
      - name: login docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: push image to docker hub
        run: docker push $DOCKER_USERNAME/$PROJECT_NAME-auth
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
      - name: change kubectl context to digitalocean
        run: doctl kubernetes cluster kubeconfig save $PROJECT_NAME
      
      - name: update deployment
        run: kubectl rollout restart deployment auth-deployment