name: deploy-query

# Manual event
on: workflow_dispatch 

jobs:
  build:
    name: deploy query service
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code on the repository
        uses: actions/checkout@v2

      - name: build docker image
        run: cd query && docker build -t $DOCKER_USERNAME/passmanager-query .
      
      - name: login docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: push image to docker hub
        run: docker push $DOCKER_USERNAME/passmanager-query
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
      - name: change kubectl context to digitalocean
        run: doctl kubernetes cluster kubeconfig save passmanager
      
      - name: update deployment
        run: kubectl rollout restart deployment query-deployment