name: tests-auth

on:
  workflow_dispatch:
  push:
    branches:
      - main 
    paths:
      - "auth/**"

jobs:
  build:
    name: testing auth service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run unit testing of auth
        uses: cd auth && npm install && npm run test:ci